name: Daily arXiv
on:
  schedule:
    # Run daily at 17:00
    - cron: '0 17 * * *'
  workflow_dispatch:
    # Allow to run the action manually
jobs:
  andromeda-papers:
    runs-on: ubuntu-latest
    env:
      MASTODON_ANDROMEDAFEED_TOKEN: ${{ secrets.MASTODON_ANDROMEDAFEED_TOKEN }}
      NASA_APOD_API_KEY: ${{ secrets.NASA_APOD_API_KEY }}
      TW_ANDROMEDAFEED_ACCESS_TOKEN: ${{ secrets.TW_ANDROMEDAFEED_ACCESS_TOKEN }}
      TW_ANDROMEDAFEED_ACCESS_TOKEN_SECRET: ${{ secrets.TW_ANDROMEDAFEED_ACCESS_TOKEN_SECRET }}
      TW_ANDROMEDAFEED_API_KEY: ${{ secrets.TW_ANDROMEDAFEED_API_KEY }}
      TW_ANDROMEDAFEED_API_SECRET_KEY: ${{ secrets.TW_ANDROMEDAFEED_API_SECRET_KEY }}
      BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
    steps:
      - name: Checkout Andromeda Feed
        uses: actions/checkout@v4
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: true
      - name: Check arXiv
        run: bundle exec rake andromeda:update_papers
