name: Daily APOD
on:
  schedule:
    # Run daily at 09:00
    - cron: '0 9 * * *'
  workflow_dispatch:
    # Allow to run the action manually
jobs:
  andromeda-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Andromeda Feed
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true
      - name: Check APOD
        run: bundle exec rake andromeda:update_apod
